require_relative "Abstract";

class ASTInterface; extend Abstract;
    abstract_methods :empty,
                     :first_unit,
                     :translation_unit,
                     :base_ten_literal,
                     :alternate_base_literal,
                     :big_integer_literal,
                     :big_float_literal,
                     :string_literal,
                     :symbol_literal,
                     :symbol_name,
                     :tuple_literal,
                     :tuple_item,
                     :hash_literal,
                     :association,
                     :json_association,
                     :quoted_list_literal,
                     :block_literal,
                     :variable,
                     :list,
                     :expression,
                     :assignment_message,
                     :message,
                     :unary_message,

                     :cascaded_message,

                     :terminal_UNSIGNED_BASE_TEN_NUMBER,
                     :terminal_ALTERNATE_BASE_NUMBER,
                     :terminal_BIGINTEGER,
                     :terminal_BIGFLOAT,
                     :terminal_STRING,
                     :terminal_UNQUOTED_STRING,
                     :terminal_IDENTIFIER,
                     :terminal_MESSAGE_SYMBOL,
                     :terminal_IDENTIFIER_SYMBOL,
                     :terminal_INSTANCE_SYMBOL,
                     :terminal_SIGN,
                     :terminal_EQUALS;
end
