#ifndef __HASHES_SPEC_H_
#define __HASHES_SPEC_H_

#include "../_helpers.h"

module(hashes_spec, {
    it("parses hash literals", {
        parse("({})", marg_vector_new(FM_HASH, marg_string_new("0")));
        parse("({a: {}, b: {}})", marg_vector_new(FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("a"), FM_HASH, marg_string_new("0"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("b"), FM_HASH, marg_string_new("0"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("2")));
        parse("({a: 1, b: 2, c: 3})", marg_vector_new(FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("a"), FM_1, FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("b"), FM_2, FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("c"), FM_INTEGER, marg_string_new("3"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("3")));
        parse("{\"a\": 1, \"b\": 2, \"c\": 3}", marg_vector_new(FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("a"), FM_1, FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("b"), FM_2, FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("c"), FM_INTEGER, marg_string_new("3"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("3")));
        parse("({\"k1\": \"v1\", \"k2\": \"v2\", \"k3\": \"v3\"})", marg_vector_new(FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("k1"), FM_STRING, marg_string_new("v1"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("k2"), FM_STRING, marg_string_new("v2"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("k3"), FM_STRING, marg_string_new("v3"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("3")));
        parse("{x: {a: 1, b: 2}, y: {c: 3, d: 4}}", marg_vector_new(FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("x"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("a"), FM_1, FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("b"), FM_2, FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("2"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("y"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("c"), FM_INTEGER, marg_string_new("3"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("d"), FM_INTEGER, marg_string_new("4"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("2"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("2")));
        parse("{a: 42 factorial, b: 2 + 3, c: 41 plus: 1, d: (42 incr decr, 41 incr)}", marg_vector_new(FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("a"), FM_INTEGER, marg_string_new("42"), FM_UNARY, marg_string_new("factorial"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("b"), FM_2, FM_INTEGER, marg_string_new("3"), FM_BINARY, marg_string_new("+"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("c"), FM_INTEGER, marg_string_new("41"), FM_1, FM_KEYWORD, marg_string_new("plus:"), marg_string_new("1"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_VARIABLE, marg_string_new("Association"), FM_STRING, marg_string_new("d"), FM_INTEGER, marg_string_new("42"), FM_UNARY, marg_string_new("incr"), FM_UNARY, marg_string_new("decr"), FM_INTEGER, marg_string_new("41"), FM_UNARY, marg_string_new("incr"), FM_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), FM_HASH, marg_string_new("4")));
    });

    it("parses hashes", {
        parse("(x at: 'a' put: 3)", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_CHAR, marg_string_new("a"), FM_INTEGER, marg_string_new("3"), FM_KEYWORD, marg_string_new("at:put:"), marg_string_new("2")));
        parse("(x is_empty?)", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_UNARY, marg_string_new("is_empty?")));
        parse("(x size)", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_UNARY, marg_string_new("size")));
        parse("(x at: \"a\" if_absent: \"\")", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_STRING, marg_string_new("a"), FM_STRING, marg_string_new(""), FM_KEYWORD, marg_string_new("at:if_absent:"), marg_string_new("2")));
        parse("(x key_at_value: 3 if_absent: \"\")", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_INTEGER, marg_string_new("3"), FM_STRING, marg_string_new(""), FM_KEYWORD, marg_string_new("key_at_value:if_absent:"), marg_string_new("2")));
        parse("(x remove_key: \"e\" if_absent: \"\")", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_STRING, marg_string_new("e"), FM_STRING, marg_string_new(""), FM_KEYWORD, marg_string_new("remove_key:if_absent:"), marg_string_new("2")));
        parse("(b = x includes_key: \"a\")", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_STRING, marg_string_new("a"), FM_KEYWORD, marg_string_new("includes_key:"), marg_string_new("1"), FM_STORE, marg_string_new("b")));
        parse("(x keys puts)", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_UNARY, marg_string_new("keys"), FM_UNARY, marg_string_new("puts")));
        parse("(x values puts)", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_UNARY, marg_string_new("values"), FM_UNARY, marg_string_new("puts")));
        parse("(x each_key: {a | a puts})", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_START_PROC, FM_VARIABLE, marg_string_new("a"), FM_TENSOR, marg_string_new("1"), FM_VARIABLE, marg_string_new("a"), FM_UNARY, marg_string_new("puts"), FM_END_PROC, FM_KEYWORD, marg_string_new("each_key:"), marg_string_new("1")));
        parse("(x each_value: {a | a puts})", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_START_PROC, FM_VARIABLE, marg_string_new("a"), FM_TENSOR, marg_string_new("1"), FM_VARIABLE, marg_string_new("a"), FM_UNARY, marg_string_new("puts"), FM_END_PROC, FM_KEYWORD, marg_string_new("each_value:"), marg_string_new("1")));
        parse("(x each: {a | a puts})", marg_vector_new(FM_VARIABLE, marg_string_new("x"), FM_START_PROC, FM_VARIABLE, marg_string_new("a"), FM_TENSOR, marg_string_new("1"), FM_VARIABLE, marg_string_new("a"), FM_UNARY, marg_string_new("puts"), FM_END_PROC, FM_KEYWORD, marg_string_new("each:"), marg_string_new("1")));
    });
})

#endif
