#ifndef __HASHES_SPEC_H_
#define __HASHES_SPEC_H_

#include "../_helpers.h"

module(hashes_spec, {
    it("parses hash literals", {
        parse("({})", marg_vector_new(OP_PUSH_HASH, marg_string_new("0")));
        parse("({a: {}, b: {}})", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_PUSH_HASH, marg_string_new("0"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"b\""), OP_PUSH_HASH, marg_string_new("0"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("2")));
        parse("({a: 1, b: 2, c: 3})", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_PUSH_1, OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"b\""), OP_PUSH_2, OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"c\""), OP_PUSH_INTEGER, marg_string_new("3"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("3")));
        parse("{\"a\": 1, \"b\": 2, \"c\": 3}", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_PUSH_1, OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"b\""), OP_PUSH_2, OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"c\""), OP_PUSH_INTEGER, marg_string_new("3"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("3")));
        parse("({\"k1\": \"v1\", \"k2\": \"v2\", \"k3\": \"v3\"})", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"k1\""), OP_PUSH_STRING, marg_string_new("\"v1\""), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"k2\""), OP_PUSH_STRING, marg_string_new("\"v2\""), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"k3\""), OP_PUSH_STRING, marg_string_new("\"v3\""), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("3")));
        parse("{x: {a: 1, b: 2}, y: {c: 3, d: 4}}", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"x\""), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_PUSH_1, OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"b\""), OP_PUSH_2, OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("2"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"y\""), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"c\""), OP_PUSH_INTEGER, marg_string_new("3"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"d\""), OP_PUSH_INTEGER, marg_string_new("4"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("2"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("2")));
        parse("{a: 42 factorial, b: 2 + 3, c: 41 plus: 1, d: (42 incr decr, 41 incr)}", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_PUSH_INTEGER, marg_string_new("42"), OP_UNARY, marg_string_new("factorial"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"b\""), OP_PUSH_2, OP_PUSH_INTEGER, marg_string_new("3"), OP_BINARY, marg_string_new("+"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"c\""), OP_PUSH_INTEGER, marg_string_new("41"), OP_PUSH_1, OP_KEYWORD, marg_string_new("plus:"), marg_string_new("1"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_VARIABLE, marg_string_new("Association"), OP_PUSH_STRING, marg_string_new("\"d\""), OP_PUSH_INTEGER, marg_string_new("42"), OP_UNARY, marg_string_new("incr"), OP_UNARY, marg_string_new("decr"), OP_PUSH_INTEGER, marg_string_new("41"), OP_UNARY, marg_string_new("incr"), OP_KEYWORD, marg_string_new("key:value:"), marg_string_new("2"), OP_PUSH_HASH, marg_string_new("4")));
    });

    it("parses hashes", {
        parse("(x at: 'a' put: 3)", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_PUSH_CHAR, marg_string_new("'a'"), OP_PUSH_INTEGER, marg_string_new("3"), OP_KEYWORD, marg_string_new("at:put:"), marg_string_new("2")));
        parse("(x is_empty?)", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_UNARY, marg_string_new("is_empty?")));
        parse("(x size)", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_UNARY, marg_string_new("size")));
        parse("(x at: \"a\" if_absent: \"\")", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_PUSH_STRING, marg_string_new("\"\""), OP_KEYWORD, marg_string_new("at:if_absent:"), marg_string_new("2")));
        parse("(x key_at_value: 3 if_absent: \"\")", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_PUSH_INTEGER, marg_string_new("3"), OP_PUSH_STRING, marg_string_new("\"\""), OP_KEYWORD, marg_string_new("key_at_value:if_absent:"), marg_string_new("2")));
        parse("(x remove_key: \"e\" if_absent: \"\")", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_PUSH_STRING, marg_string_new("\"e\""), OP_PUSH_STRING, marg_string_new("\"\""), OP_KEYWORD, marg_string_new("remove_key:if_absent:"), marg_string_new("2")));
        parse("(b = x includes_key: \"a\")", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_PUSH_STRING, marg_string_new("\"a\""), OP_KEYWORD, marg_string_new("includes_key:"), marg_string_new("1"), OP_STORE, marg_string_new("b")));
        parse("(x keys puts)", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_UNARY, marg_string_new("keys"), OP_UNARY, marg_string_new("puts")));
        parse("(x values puts)", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_UNARY, marg_string_new("values"), OP_UNARY, marg_string_new("puts")));
        parse("(x each_key: {a | a puts})", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_START_PUSH_PROC, OP_PUSH_VARIABLE, marg_string_new("a"), OP_PUSH_TENSOR, marg_string_new("1"), OP_PUSH_VARIABLE, marg_string_new("a"), OP_UNARY, marg_string_new("puts"), OP_END_PUSH_PROC, OP_KEYWORD, marg_string_new("each_key:"), marg_string_new("1")));
        parse("(x each_value: {a | a puts})", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_START_PUSH_PROC, OP_PUSH_VARIABLE, marg_string_new("a"), OP_PUSH_TENSOR, marg_string_new("1"), OP_PUSH_VARIABLE, marg_string_new("a"), OP_UNARY, marg_string_new("puts"), OP_END_PUSH_PROC, OP_KEYWORD, marg_string_new("each_value:"), marg_string_new("1")));
        parse("(x each: {a | a puts})", marg_vector_new(OP_PUSH_VARIABLE, marg_string_new("x"), OP_START_PUSH_PROC, OP_PUSH_VARIABLE, marg_string_new("a"), OP_PUSH_TENSOR, marg_string_new("1"), OP_PUSH_VARIABLE, marg_string_new("a"), OP_UNARY, marg_string_new("puts"), OP_END_PUSH_PROC, OP_KEYWORD, marg_string_new("each:"), marg_string_new("1")));
    });
})

#endif
