#ifndef __DISPATCH_TABLE_H_
#define __DISPATCH_TABLE_H_

#define dispatch_table()                \
  static void *_computed_gotos[256] = { \
    &&_computed_goto_OP_NIL,            \
    &&_computed_goto_OP_FALSE,          \
    &&_computed_goto_OP_TRUE,           \
    &&_computed_goto_OP_NUMBER,         \
    &&_computed_goto_OP_STRING,         \
    &&_computed_goto_OP_ADD,            \
    &&_computed_goto_OP_SUB,            \
    &&_computed_goto_OP_MUL,            \
    &&_computed_goto_OP_DIV,            \
    &&_computed_goto_OP_JUMP,           \
    &&_computed_goto_OP_JUMP_IF_FALSE,  \
    &&_computed_goto_OP_PRINT,          \
    &&_computed_goto_OP_HALT,           \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR              \
  }

#endif
