#ifndef __OPCODE_H_
#define __OPCODE_H_

#define OP_NIL           0x00
#define OP_FALSE         0x01
#define OP_TRUE          0x02
#define OP_NUMBER        0x03
#define OP_STRING        0x04
#define OP_ADD           0x05
#define OP_SUB           0x06
#define OP_MUL           0x07
#define OP_DIV           0x08
#define OP_JUMP          0x09
#define OP_JUMP_IF_FALSE 0x0a
#define OP_PRINT         0x0b
#define OP_HALT          0x0c

#define dispatch_table()                \
  static void *_computed_gotos[256] = { \
    &&_computed_goto_OP_NIL,            \
    &&_computed_goto_OP_FALSE,          \
    &&_computed_goto_OP_TRUE,           \
    &&_computed_goto_OP_NUMBER,         \
    &&_computed_goto_OP_STRING,         \
    &&_computed_goto_OP_ADD,            \
    &&_computed_goto_OP_SUB,            \
    &&_computed_goto_OP_MUL,            \
    &&_computed_goto_OP_DIV,            \
    &&_computed_goto_OP_JUMP,           \
    &&_computed_goto_OP_JUMP_IF_FALSE,  \
    &&_computed_goto_OP_PRINT,          \
    &&_computed_goto_OP_HALT,           \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR,             \
    &&_computed_goto_ERROR              \
  }

#endif
